# Generated by Django 2.0.13 on 2019-04-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='공유하고 싶은 item의 이름을 입력해주세요.', max_length=20)),
                ('photo', models.ImageField(upload_to='')),
                ('deposit', models.IntegerField()),
                ('rentalFeePerHour', models.IntegerField()),
                ('currentStatus', models.CharField(choices=[('A', '이용 가능'), ('R', '수리중'), ('S', '공유중'), ('B', '고장')], default='A', max_length=10)),
                ('shippingMethod', models.CharField(choices=[('D', '직접 거래'), ('S', '택배'), ('B', '직접거래/택배')], default='D', max_length=10)),
                ('location', models.CharField(max_length=30)),
                ('maxRentTime', models.IntegerField()),
                ('explanation', models.TextField()),
                ('uploadDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('B', '도서/서적'), ('C', '캠핑/레져'), ('L', '생활/가전'), ('W', '의류/패션'), ('E', '사물/잡화')], default='E', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='itemType',
            field=models.ManyToManyField(to='item.ItemType'),
        ),
    ]
