# Generated by Django 2.0.13 on 2019-04-21 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('itemId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='공유하고 싶은 item의 이름을 입력해주세요.', max_length=20)),
                ('photo', models.ImageField(upload_to='')),
                ('deposit', models.IntegerField()),
                ('rentalFeePerHour', models.IntegerField()),
                ('currentStatus', models.CharField(choices=[('A', '이용 가능'), ('R', '수리중'), ('S', '공유중'), ('B', '고장')], default='A', max_length=10)),
                ('shippingMethod', models.CharField(choices=[('D', '직접 거래'), ('S', '택배'), ('B', '직접거래/택배')], default='D', max_length=10)),
                ('location', models.CharField(max_length=30)),
                ('maxRentTime', models.IntegerField()),
                ('explanation', models.TextField()),
                ('uploadDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sharer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userMail', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='itemType',
            field=models.ManyToManyField(to='item.ItemType'),
        ),
        migrations.AddField(
            model_name='items',
            name='userMail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='item.Sharer'),
        ),
    ]
