# Generated by Django 2.2 on 2019-05-12 23:51

from django.db import migrations, models
import django.utils.timezone
import item.models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='thumname_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
