# Generated by Django 2.2 on 2019-05-14 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20190515_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='thumname_image',
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
