# Generated by Django 2.0.13 on 2019-05-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_auto_20190515_0745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='tag_set',
            field=models.ManyToManyField(blank=True, to='item.Tag'),
        ),
    ]
