# Generated by Django 2.0.13 on 2019-04-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='extensionTime',
            field=models.DateTimeField(null=True),
        ),
    ]
