# Generated by Django 2.0.13 on 2019-04-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_auto_20190427_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='returnTime',
            field=models.DateTimeField(null=True),
        ),
    ]
