# Generated by Django 2.0.13 on 2019-06-04 11:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_auto_20190427_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='reserationTime',
            new_name='reservationTime',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='dueDate',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='dueTime',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='rentDate',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='rentTime',
        ),
        migrations.AddField(
            model_name='rent',
            name='dueDateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 4, 11, 57, 14, 334586, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='rent',
            name='rentDateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 4, 11, 57, 14, 334586, tzinfo=utc)),
        ),
    ]
