# Generated by Django 2.0.13 on 2019-06-04 11:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_auto_20190604_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='dueDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rent',
            name='rentDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
