# Generated by Django 2.0.13 on 2019-04-20 04:54

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email address')),
                ('nickname', models.CharField(max_length=30, unique=True, verbose_name='Nickname')),
                ('location', models.CharField(max_length=30, verbose_name='Location')),
                ('is_sharer', models.BooleanField(default=False, verbose_name='Is sharer')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date joined')),
                ('salt', models.CharField(blank=True, max_length=10, verbose_name='Salt')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ('-date_joined',),
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
