# Generated by Django 2.0.13 on 2019-04-20 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_items_itemtype_sharer'),
        ('main', '0002_auto_20190414_1718'),
    ]

    operations = [
    ]
