# Generated by Django 2.0.13 on 2019-04-21 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_merge_20190420_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='itemType',
        ),
        migrations.RemoveField(
            model_name='items',
            name='userMail',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.DeleteModel(
            name='ItemType',
        ),
        migrations.DeleteModel(
            name='Sharer',
        ),
    ]
